apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kijani-staging

resources:
  - ../../base
  - ingress.yml
  - ../../observability

configMapGenerator:
  - name: kk-payments-config
    envs:
      - kk-payments.properties

labels:
  - pairs:
      kijani.io/environment: staging
    includeSelectors: false
